[package]
name = "sc-protocol"
version.workspace = true
edition.workspace = true

[dependencies]
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
bytes = "1"

[build-dependencies]
prost-build = { workspace = true }
